//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://tinkoff.ru/partners/insurance/investing/types", ClrNamespace = "tinkoff.ru.partners.insurance.investing.types")]



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/0.1", ConfigurationName = "InvestingInsuranceInterface")]
public interface InvestingInsuranceInterface
{

    // CODEGEN: Контракт генерации сообщений с операцией getProducts не является ни RPC, ни упакованным документом.
    [System.ServiceModel.OperationContractAttribute(Action = "")]
    [System.ServiceModel.FaultContractAttribute(typeof(tinkoff.ru.partners.insurance.investing.types.CommonFault), Action = "", Name = "CommonFault", Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getProductsResponse getProducts(getProductsRequest1 request);

    // CODEGEN: Контракт генерации сообщений с операцией getQuotes не является ни RPC, ни упакованным документом.
    [System.ServiceModel.OperationContractAttribute(Action = "")]
    [System.ServiceModel.FaultContractAttribute(typeof(tinkoff.ru.partners.insurance.investing.types.CommonFault), Action = "", Name = "CommonFault", Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getQuotesResponse1 getQuotes(getQuotesRequest1 request);

    // CODEGEN: Контракт генерации сообщений с операцией createPolicy не является ни RPC, ни упакованным документом.
    [System.ServiceModel.OperationContractAttribute(Action = "")]
    [System.ServiceModel.FaultContractAttribute(typeof(tinkoff.ru.partners.insurance.investing.types.CommonFault), Action = "", Name = "CommonFault", Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    createPolicyResponse1 createPolicy(createPolicyRequest1 request);

    // CODEGEN: Контракт генерации сообщений с операцией getPolicy не является ни RPC, ни упакованным документом.
    [System.ServiceModel.OperationContractAttribute(Action = "")]
    [System.ServiceModel.FaultContractAttribute(typeof(tinkoff.ru.partners.insurance.investing.types.CommonFault), Action = "", Name = "CommonFault", Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getPolicyResponse1 getPolicy(getPolicyRequest1 request);

    // CODEGEN: Контракт генерации сообщений с операцией getPolicyDocumentsList не является ни RPC, ни упакованным документом.
    [System.ServiceModel.OperationContractAttribute(Action = "")]
    [System.ServiceModel.FaultContractAttribute(typeof(tinkoff.ru.partners.insurance.investing.types.CommonFault), Action = "", Name = "CommonFault", Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getPolicyDocumentsListResponse getPolicyDocumentsList(getPolicyDocumentsListRequest1 request);

    // CODEGEN: Контракт генерации сообщений с операцией getPolicyDocument не является ни RPC, ни упакованным документом.
    [System.ServiceModel.OperationContractAttribute(Action = "")]
    [System.ServiceModel.FaultContractAttribute(typeof(tinkoff.ru.partners.insurance.investing.types.CommonFault), Action = "", Name = "CommonFault", Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    getPolicyDocumentResponse1 getPolicyDocument(getPolicyDocumentRequest1 request);

    // CODEGEN: Контракт генерации сообщений с операцией acceptPolicy не является ни RPC, ни упакованным документом.
    [System.ServiceModel.OperationContractAttribute(Action = "")]
    [System.ServiceModel.FaultContractAttribute(typeof(tinkoff.ru.partners.insurance.investing.types.CommonFault), Action = "", Name = "CommonFault", Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    acceptPolicyResponse1 acceptPolicy(acceptPolicyRequest1 request);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class GetProductsRequest
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class AcceptPolicyResponse
{

    private string resultField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string result
    {
        get
        {
            return this.resultField;
        }
        set
        {
            this.resultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class AcceptPolicyRequest
{

    private string policyIdField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string policyId
    {
        get
        {
            return this.policyIdField;
        }
        set
        {
            this.policyIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class GetPolicyDocumentResponse
{

    private byte[] documentDataField;

    private string documentTypeField;

    private string documentNameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "base64Binary", Order = 0)]
    public byte[] documentData
    {
        get
        {
            return this.documentDataField;
        }
        set
        {
            this.documentDataField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string documentType
    {
        get
        {
            return this.documentTypeField;
        }
        set
        {
            this.documentTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public string documentName
    {
        get
        {
            return this.documentNameField;
        }
        set
        {
            this.documentNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class GetPolicyDocumentRequest
{

    private string policyIdField;

    private string documentIdField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string policyId
    {
        get
        {
            return this.policyIdField;
        }
        set
        {
            this.policyIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string documentId
    {
        get
        {
            return this.documentIdField;
        }
        set
        {
            this.documentIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class document
{

    private string idField;

    private string nameField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class GetPolicyDocumentsListRequest
{

    private string policyIdField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string policyId
    {
        get
        {
            return this.policyIdField;
        }
        set
        {
            this.policyIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class redemptionAmountInfo
{

    private System.DateTime dateField;

    private decimal sumField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 0)]
    public System.DateTime date
    {
        get
        {
            return this.dateField;
        }
        set
        {
            this.dateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public decimal sum
    {
        get
        {
            return this.sumField;
        }
        set
        {
            this.sumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class paymentsPlanItem
{

    private System.DateTime dateField;

    private decimal sumField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 0)]
    public System.DateTime date
    {
        get
        {
            return this.dateField;
        }
        set
        {
            this.dateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public decimal sum
    {
        get
        {
            return this.sumField;
        }
        set
        {
            this.sumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class GetPolicyResponse
{

    private string productIdField;

    private string productNameField;

    private string policyIdField;

    private string policyNumberField;

    private string fullDescriptionField;

    private System.DateTime effectiveDateField;

    private System.DateTime expirationDateField;

    private string coefficientField;

    private decimal profitabilityField;

    private string statusField;

    private currency currencyField;

    private decimal amountField;

    private string coverCapitalField;

    private string strategyField;

    private paymentsPlanItem[] paymentsPlanField;

    private risk[] insuranceRisksField;

    private redemptionAmountInfo[] redemptionAmountsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string productId
    {
        get
        {
            return this.productIdField;
        }
        set
        {
            this.productIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string productName
    {
        get
        {
            return this.productNameField;
        }
        set
        {
            this.productNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public string policyId
    {
        get
        {
            return this.policyIdField;
        }
        set
        {
            this.policyIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
    public string policyNumber
    {
        get
        {
            return this.policyNumberField;
        }
        set
        {
            this.policyNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
    public string fullDescription
    {
        get
        {
            return this.fullDescriptionField;
        }
        set
        {
            this.fullDescriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 5)]
    public System.DateTime effectiveDate
    {
        get
        {
            return this.effectiveDateField;
        }
        set
        {
            this.effectiveDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 6)]
    public System.DateTime expirationDate
    {
        get
        {
            return this.expirationDateField;
        }
        set
        {
            this.expirationDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
    public string coefficient
    {
        get
        {
            return this.coefficientField;
        }
        set
        {
            this.coefficientField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
    public decimal profitability
    {
        get
        {
            return this.profitabilityField;
        }
        set
        {
            this.profitabilityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
    public string status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
    public currency currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
    public decimal amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
    public string coverCapital
    {
        get
        {
            return this.coverCapitalField;
        }
        set
        {
            this.coverCapitalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
    public string strategy
    {
        get
        {
            return this.strategyField;
        }
        set
        {
            this.strategyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("paymentsPlan", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
    public paymentsPlanItem[] paymentsPlan
    {
        get
        {
            return this.paymentsPlanField;
        }
        set
        {
            this.paymentsPlanField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("insuranceRisks", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
    public risk[] insuranceRisks
    {
        get
        {
            return this.insuranceRisksField;
        }
        set
        {
            this.insuranceRisksField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("redemptionAmounts", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 16)]
    public redemptionAmountInfo[] redemptionAmounts
    {
        get
        {
            return this.redemptionAmountsField;
        }
        set
        {
            this.redemptionAmountsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public enum currency
{

    /// <remarks/>
    RUR,

    /// <remarks/>
    USD,

    /// <remarks/>
    EUR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class risk
{

    private string idField;

    private string textField;

    private string sumField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public string sum
    {
        get
        {
            return this.sumField;
        }
        set
        {
            this.sumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class GetPolicyRequest
{

    private string policyIdField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string policyId
    {
        get
        {
            return this.policyIdField;
        }
        set
        {
            this.policyIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class CreatePolicyResponse
{

    private string policyNumberField;

    private string policyIdField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string policyNumber
    {
        get
        {
            return this.policyNumberField;
        }
        set
        {
            this.policyNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string policyId
    {
        get
        {
            return this.policyIdField;
        }
        set
        {
            this.policyIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class address
{

    private addressType typeField;

    private string countryField;

    private string indexField;

    private string regionField;

    private string districtField;

    private string cityField;

    private string localityField;

    private string streetField;

    private string houseField;

    private string buildingField;

    private string flatField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public addressType type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string country
    {
        get
        {
            return this.countryField;
        }
        set
        {
            this.countryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public string index
    {
        get
        {
            return this.indexField;
        }
        set
        {
            this.indexField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
    public string region
    {
        get
        {
            return this.regionField;
        }
        set
        {
            this.regionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
    public string district
    {
        get
        {
            return this.districtField;
        }
        set
        {
            this.districtField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
    public string city
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
    public string locality
    {
        get
        {
            return this.localityField;
        }
        set
        {
            this.localityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
    public string street
    {
        get
        {
            return this.streetField;
        }
        set
        {
            this.streetField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
    public string house
    {
        get
        {
            return this.houseField;
        }
        set
        {
            this.houseField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
    public string building
    {
        get
        {
            return this.buildingField;
        }
        set
        {
            this.buildingField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
    public string flat
    {
        get
        {
            return this.flatField;
        }
        set
        {
            this.flatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public enum addressType
{

    /// <remarks/>
    residence,

    /// <remarks/>
    registration,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(beneficiary))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class person
{

    private string lastNameField;

    private string firstNameField;

    private string patronymicNameField;

    private string documentSerieField;

    private string documentNumberField;

    private System.DateTime documentIssueDateField;

    private bool documentIssueDateFieldSpecified;

    private string documentOrganisationField;

    private string documentOrganisationCodeField;

    private System.DateTime dateOfBirthField;

    private string placeOfBirthField;

    private sex sexField;

    private string innField;

    private address[] addressesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string lastName
    {
        get
        {
            return this.lastNameField;
        }
        set
        {
            this.lastNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string firstName
    {
        get
        {
            return this.firstNameField;
        }
        set
        {
            this.firstNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public string patronymicName
    {
        get
        {
            return this.patronymicNameField;
        }
        set
        {
            this.patronymicNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
    public string documentSerie
    {
        get
        {
            return this.documentSerieField;
        }
        set
        {
            this.documentSerieField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
    public string documentNumber
    {
        get
        {
            return this.documentNumberField;
        }
        set
        {
            this.documentNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 5)]
    public System.DateTime documentIssueDate
    {
        get
        {
            return this.documentIssueDateField;
        }
        set
        {
            this.documentIssueDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool documentIssueDateSpecified
    {
        get
        {
            return this.documentIssueDateFieldSpecified;
        }
        set
        {
            this.documentIssueDateFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
    public string documentOrganisation
    {
        get
        {
            return this.documentOrganisationField;
        }
        set
        {
            this.documentOrganisationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
    public string documentOrganisationCode
    {
        get
        {
            return this.documentOrganisationCodeField;
        }
        set
        {
            this.documentOrganisationCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 8)]
    public System.DateTime dateOfBirth
    {
        get
        {
            return this.dateOfBirthField;
        }
        set
        {
            this.dateOfBirthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
    public string placeOfBirth
    {
        get
        {
            return this.placeOfBirthField;
        }
        set
        {
            this.placeOfBirthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
    public sex sex
    {
        get
        {
            return this.sexField;
        }
        set
        {
            this.sexField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
    public string inn
    {
        get
        {
            return this.innField;
        }
        set
        {
            this.innField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("addresses", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
    public address[] addresses
    {
        get
        {
            return this.addressesField;
        }
        set
        {
            this.addressesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public enum sex
{

    /// <remarks/>
    male,

    /// <remarks/>
    female,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class beneficiary : person
{

    private sex sex1Field;

    private bool sex1FieldSpecified;

    private relationType relationField;

    private bool relationFieldSpecified;

    private decimal percentField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sex", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public sex sex1
    {
        get
        {
            return this.sex1Field;
        }
        set
        {
            this.sex1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sex1Specified
    {
        get
        {
            return this.sex1FieldSpecified;
        }
        set
        {
            this.sex1FieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public relationType relation
    {
        get
        {
            return this.relationField;
        }
        set
        {
            this.relationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool relationSpecified
    {
        get
        {
            return this.relationFieldSpecified;
        }
        set
        {
            this.relationFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public decimal percent
    {
        get
        {
            return this.percentField;
        }
        set
        {
            this.percentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public enum relationType
{

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("7")]
    Item7,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("8")]
    Item8,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("9")]
    Item9,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("10")]
    Item10,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("11")]
    Item11,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("12")]
    Item12,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("13")]
    Item13,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("14")]
    Item14,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("15")]
    Item15,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("16")]
    Item16,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class CreatePolicyRequest
{

    private string applicationIdField;

    private string productIdField;

    private currency currencyField;

    private string policyTermField;

    private periodicity periodicityOfContributionsField;

    private periodicity periodicitiesOfPaymentsField;

    private bool periodicitiesOfPaymentsFieldSpecified;

    private string strategyIdField;

    private decimal coverCapitalField;

    private bool coverCapitalFieldSpecified;

    private decimal amountField;

    private person insurantField;

    private person insuredField;

    private bool insurantIsInsuredField;

    private beneficiary[] beneficiariesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string applicationId
    {
        get
        {
            return this.applicationIdField;
        }
        set
        {
            this.applicationIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string productId
    {
        get
        {
            return this.productIdField;
        }
        set
        {
            this.productIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public currency currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer", Order = 3)]
    public string policyTerm
    {
        get
        {
            return this.policyTermField;
        }
        set
        {
            this.policyTermField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
    public periodicity periodicityOfContributions
    {
        get
        {
            return this.periodicityOfContributionsField;
        }
        set
        {
            this.periodicityOfContributionsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
    public periodicity periodicitiesOfPayments
    {
        get
        {
            return this.periodicitiesOfPaymentsField;
        }
        set
        {
            this.periodicitiesOfPaymentsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool periodicitiesOfPaymentsSpecified
    {
        get
        {
            return this.periodicitiesOfPaymentsFieldSpecified;
        }
        set
        {
            this.periodicitiesOfPaymentsFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
    public string strategyId
    {
        get
        {
            return this.strategyIdField;
        }
        set
        {
            this.strategyIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
    public decimal coverCapital
    {
        get
        {
            return this.coverCapitalField;
        }
        set
        {
            this.coverCapitalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool coverCapitalSpecified
    {
        get
        {
            return this.coverCapitalFieldSpecified;
        }
        set
        {
            this.coverCapitalFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
    public decimal amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
    public person insurant
    {
        get
        {
            return this.insurantField;
        }
        set
        {
            this.insurantField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
    public person insured
    {
        get
        {
            return this.insuredField;
        }
        set
        {
            this.insuredField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
    public bool insurantIsInsured
    {
        get
        {
            return this.insurantIsInsuredField;
        }
        set
        {
            this.insurantIsInsuredField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("beneficiaries", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
    public beneficiary[] beneficiaries
    {
        get
        {
            return this.beneficiariesField;
        }
        set
        {
            this.beneficiariesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public enum periodicity
{

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("12")]
    Item12,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class quote
{

    private System.DateTime dateField;

    private decimal priceField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 0)]
    public System.DateTime date
    {
        get
        {
            return this.dateField;
        }
        set
        {
            this.dateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public decimal price
    {
        get
        {
            return this.priceField;
        }
        set
        {
            this.priceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class GetQuotesResponse
{

    private quote[] quotesField;

    private System.DateTime dateField;

    private bool dateFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("quotes", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public quote[] quotes
    {
        get
        {
            return this.quotesField;
        }
        set
        {
            this.quotesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 1)]
    public System.DateTime date
    {
        get
        {
            return this.dateField;
        }
        set
        {
            this.dateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateSpecified
    {
        get
        {
            return this.dateFieldSpecified;
        }
        set
        {
            this.dateFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class GetQuotesRequest
{

    private string productIdField;

    private string strategyIdField;

    private System.DateTime dateFromField;

    private System.DateTime dateToField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string productId
    {
        get
        {
            return this.productIdField;
        }
        set
        {
            this.productIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string strategyId
    {
        get
        {
            return this.strategyIdField;
        }
        set
        {
            this.strategyIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 2)]
    public System.DateTime dateFrom
    {
        get
        {
            return this.dateFromField;
        }
        set
        {
            this.dateFromField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "date", Order = 3)]
    public System.DateTime dateTo
    {
        get
        {
            return this.dateToField;
        }
        set
        {
            this.dateToField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class investParam
{

    private string strategyIdField;

    private string strategyField;

    private periodicity contributionsPeriodicityField;

    private periodicity paymentsPeriodicitiesField;

    private bool paymentsPeriodicitiesFieldSpecified;

    private string policyTermField;

    private decimal coverCapitalField;

    private bool coverCapitalFieldSpecified;

    private currency currencyInvestField;

    private decimal coefficientField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string strategyId
    {
        get
        {
            return this.strategyIdField;
        }
        set
        {
            this.strategyIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string strategy
    {
        get
        {
            return this.strategyField;
        }
        set
        {
            this.strategyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public periodicity contributionsPeriodicity
    {
        get
        {
            return this.contributionsPeriodicityField;
        }
        set
        {
            this.contributionsPeriodicityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
    public periodicity paymentsPeriodicities
    {
        get
        {
            return this.paymentsPeriodicitiesField;
        }
        set
        {
            this.paymentsPeriodicitiesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool paymentsPeriodicitiesSpecified
    {
        get
        {
            return this.paymentsPeriodicitiesFieldSpecified;
        }
        set
        {
            this.paymentsPeriodicitiesFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer", Order = 4)]
    public string policyTerm
    {
        get
        {
            return this.policyTermField;
        }
        set
        {
            this.policyTermField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
    public decimal coverCapital
    {
        get
        {
            return this.coverCapitalField;
        }
        set
        {
            this.coverCapitalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool coverCapitalSpecified
    {
        get
        {
            return this.coverCapitalFieldSpecified;
        }
        set
        {
            this.coverCapitalFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
    public currency currencyInvest
    {
        get
        {
            return this.currencyInvestField;
        }
        set
        {
            this.currencyInvestField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
    public decimal coefficient
    {
        get
        {
            return this.coefficientField;
        }
        set
        {
            this.coefficientField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class redemptionAmount
{

    private string yearField;

    private periodicity contributionsPeriodicityField;

    private periodicity paymentsPeriodicitiesField;

    private bool paymentsPeriodicitiesFieldSpecified;

    private currency currencyField;

    private string policyTermField;

    private decimal sumField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer", Order = 0)]
    public string year
    {
        get
        {
            return this.yearField;
        }
        set
        {
            this.yearField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public periodicity contributionsPeriodicity
    {
        get
        {
            return this.contributionsPeriodicityField;
        }
        set
        {
            this.contributionsPeriodicityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public periodicity paymentsPeriodicities
    {
        get
        {
            return this.paymentsPeriodicitiesField;
        }
        set
        {
            this.paymentsPeriodicitiesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool paymentsPeriodicitiesSpecified
    {
        get
        {
            return this.paymentsPeriodicitiesFieldSpecified;
        }
        set
        {
            this.paymentsPeriodicitiesFieldSpecified = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
    public currency currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer", Order = 4)]
    public string policyTerm
    {
        get
        {
            return this.policyTermField;
        }
        set
        {
            this.policyTermField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
    public decimal sum
    {
        get
        {
            return this.sumField;
        }
        set
        {
            this.sumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
public partial class Product
{

    private string idField;

    private string nameField;

    private string shortDescriptionField;

    private string fullDescriptionField;

    private currency currencyField;

    private string minPremiumsField;

    private string maxPremiumsField;

    private string[] policyTermOptionsField;

    private periodicity[] contributionsPeriodicityOptionsField;

    private periodicity[] paymentsPeriodicityOptionsField;

    private risk[] insuranceRisksField;

    private redemptionAmount[] redemptionAmountsField;

    private investParam[] investParamsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
    public string shortDescription
    {
        get
        {
            return this.shortDescriptionField;
        }
        set
        {
            this.shortDescriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
    public string fullDescription
    {
        get
        {
            return this.fullDescriptionField;
        }
        set
        {
            this.fullDescriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
    public currency currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
    public string minPremiums
    {
        get
        {
            return this.minPremiumsField;
        }
        set
        {
            this.minPremiumsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
    public string maxPremiums
    {
        get
        {
            return this.maxPremiumsField;
        }
        set
        {
            this.maxPremiumsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("policyTermOptions", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "integer", Order = 7)]
    public string[] policyTermOptions
    {
        get
        {
            return this.policyTermOptionsField;
        }
        set
        {
            this.policyTermOptionsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contributionsPeriodicityOptions", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
    public periodicity[] contributionsPeriodicityOptions
    {
        get
        {
            return this.contributionsPeriodicityOptionsField;
        }
        set
        {
            this.contributionsPeriodicityOptionsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("paymentsPeriodicityOptions", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
    public periodicity[] paymentsPeriodicityOptions
    {
        get
        {
            return this.paymentsPeriodicityOptionsField;
        }
        set
        {
            this.paymentsPeriodicityOptionsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("insuranceRisks", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
    public risk[] insuranceRisks
    {
        get
        {
            return this.insuranceRisksField;
        }
        set
        {
            this.insuranceRisksField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("redemptionAmounts", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
    public redemptionAmount[] redemptionAmounts
    {
        get
        {
            return this.redemptionAmountsField;
        }
        set
        {
            this.redemptionAmountsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("investParams", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
    public investParam[] investParams
    {
        get
        {
            return this.investParamsField;
        }
        set
        {
            this.investParamsField = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class getProductsRequest1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public GetProductsRequest GetProductsRequest;

    public getProductsRequest1()
    {
    }

    public getProductsRequest1(GetProductsRequest GetProductsRequest)
    {
        this.GetProductsRequest = GetProductsRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class getProductsResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetProductsResponse", Namespace = "http://tinkoff.ru/partners/insurance/investing/types", Order = 0)]
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("products", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public Product[] GetProductsResponse1;

    public getProductsResponse()
    {
    }

    public getProductsResponse(Product[] GetProductsResponse1)
    {
        this.GetProductsResponse1 = GetProductsResponse1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class getQuotesRequest1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public GetQuotesRequest GetQuotesRequest;

    public getQuotesRequest1()
    {
    }

    public getQuotesRequest1(GetQuotesRequest GetQuotesRequest)
    {
        this.GetQuotesRequest = GetQuotesRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class getQuotesResponse1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public GetQuotesResponse GetQuotesResponse;

    public getQuotesResponse1()
    {
    }

    public getQuotesResponse1(GetQuotesResponse GetQuotesResponse)
    {
        this.GetQuotesResponse = GetQuotesResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class createPolicyRequest1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public CreatePolicyRequest CreatePolicyRequest;

    public createPolicyRequest1()
    {
    }

    public createPolicyRequest1(CreatePolicyRequest CreatePolicyRequest)
    {
        this.CreatePolicyRequest = CreatePolicyRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class createPolicyResponse1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public CreatePolicyResponse CreatePolicyResponse;

    public createPolicyResponse1()
    {
    }

    public createPolicyResponse1(CreatePolicyResponse CreatePolicyResponse)
    {
        this.CreatePolicyResponse = CreatePolicyResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class getPolicyRequest1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public GetPolicyRequest GetPolicyRequest;

    public getPolicyRequest1()
    {
    }

    public getPolicyRequest1(GetPolicyRequest GetPolicyRequest)
    {
        this.GetPolicyRequest = GetPolicyRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class getPolicyResponse1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public GetPolicyResponse GetPolicyResponse;

    public getPolicyResponse1()
    {
    }

    public getPolicyResponse1(GetPolicyResponse GetPolicyResponse)
    {
        this.GetPolicyResponse = GetPolicyResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class getPolicyDocumentsListRequest1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public GetPolicyDocumentsListRequest GetPolicyDocumentsListRequest;

    public getPolicyDocumentsListRequest1()
    {
    }

    public getPolicyDocumentsListRequest1(GetPolicyDocumentsListRequest GetPolicyDocumentsListRequest)
    {
        this.GetPolicyDocumentsListRequest = GetPolicyDocumentsListRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class getPolicyDocumentsListResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetPolicyDocumentsListResponse", Namespace = "http://tinkoff.ru/partners/insurance/investing/types", Order = 0)]
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
    [System.Xml.Serialization.XmlArrayItemAttribute("documents", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public document[] GetPolicyDocumentsListResponse1;

    public getPolicyDocumentsListResponse()
    {
    }

    public getPolicyDocumentsListResponse(document[] GetPolicyDocumentsListResponse1)
    {
        this.GetPolicyDocumentsListResponse1 = GetPolicyDocumentsListResponse1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class getPolicyDocumentRequest1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public GetPolicyDocumentRequest GetPolicyDocumentRequest;

    public getPolicyDocumentRequest1()
    {
    }

    public getPolicyDocumentRequest1(GetPolicyDocumentRequest GetPolicyDocumentRequest)
    {
        this.GetPolicyDocumentRequest = GetPolicyDocumentRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class getPolicyDocumentResponse1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public GetPolicyDocumentResponse GetPolicyDocumentResponse;

    public getPolicyDocumentResponse1()
    {
    }

    public getPolicyDocumentResponse1(GetPolicyDocumentResponse GetPolicyDocumentResponse)
    {
        this.GetPolicyDocumentResponse = GetPolicyDocumentResponse;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class acceptPolicyRequest1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public AcceptPolicyRequest AcceptPolicyRequest;

    public acceptPolicyRequest1()
    {
    }

    public acceptPolicyRequest1(AcceptPolicyRequest AcceptPolicyRequest)
    {
        this.AcceptPolicyRequest = AcceptPolicyRequest;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class acceptPolicyResponse1
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tinkoff.ru/partners/insurance/investing/types", Order = 0)]
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public AcceptPolicyResponse AcceptPolicyResponse;

    public acceptPolicyResponse1()
    {
    }

    public acceptPolicyResponse1(AcceptPolicyResponse AcceptPolicyResponse)
    {
        this.AcceptPolicyResponse = AcceptPolicyResponse;
    }
}
namespace tinkoff.ru.partners.insurance.investing.types
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "GetProductsRequest", Namespace = "http://tinkoff.ru/partners/insurance/investing/types")]
    public partial class GetProductsRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    public partial class CommonFault : object, System.Xml.Serialization.IXmlSerializable
    {

        private System.Xml.XmlNode[] nodesField;

        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("CommonFault", "http://tinkoff.ru/partners/insurance/investing/types");

        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }

        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }

        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }

        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }

        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
}
